#This file stores configuration options for Oculus/Iris, such as the currently active shaderpack
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=MakeUp-UltraFast-9.5a.zip
enableShaders=true
