modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/MUKSC/TaCZTweaks/issues"
license = "GNU General Public License v3.0"

[[mods]]
modId = "tacztweaks"
version = "2.13.1"
displayName = "TaCZ Tweaks"
displayURL = "https://modrinth.com/mod/tacz-tweaks"
logoFile = "icon.png"
authors = "MUKSC"
description = '''
A collection of random tweaks and features to enhance my experience with TaCZ.'''

[[dependencies."tacztweaks"]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."tacztweaks"]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies."tacztweaks"]]
modId = "tacz"
mandatory = true
versionRange = "[1.1.7,1.1.8)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."tacztweaks"]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[4.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."tacztweaks"]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "[3.6.1+1.20,)"
ordering = "NONE"
side = "BOTH"
