import json

data = {
  "gui.tac_rogue.inventory.status": "ステータス",
  "gui.tac_rogue.inventory.perks": "パーク一覧",
  "gui.tac_rogue.inventory.floor_info": "フロア情報",
  "gui.tac_rogue.inventory.next_floor": "次の層へ",
  "gui.tac_rogue.inventory.return_lobby": "ロビーへ戻る",
  "gui.tac_rogue.inventory.vital_signs": ">> ステータス詳細",
  "gui.tac_rogue.inventory.health": "体力",
  "gui.tac_rogue.inventory.speed": "速度",
  "gui.tac_rogue.inventory.stamina": "スタミナ",
  "gui.tac_rogue.inventory.gold": "所持金: %d G",
  "gui.tac_rogue.inventory.floor": "現在層",
  "gui.tac_rogue.inventory.system_status": "システム状況:",
  "gui.tac_rogue.inventory.crafting_offline": "クラフト: ロック中",
  "gui.tac_rogue.inventory.adaptations": ">> 特殊強化 / パーク",
  "gui.tac_rogue.inventory.no_perks": "- パーク未装着",
  "gui.tac_rogue.inventory.perk_system": "解析システム:",
  "gui.tac_rogue.inventory.system_nominal": "正常稼働中",
  "gui.tac_rogue.inventory.mission_intel": ">> ミッション情報",
  "gui.tac_rogue.inventory.theme": "テーマ: %s",
  "gui.tac_rogue.inventory.objective": "目的: 全敵の殲滅",
  "gui.tac_rogue.inventory.floor_analysis": "階層分析:",
  "gui.tac_rogue.inventory.threat_high": "脅威レベル: 高",
  "gui.tac_rogue.inventory.operator_status": "作戦進行中 // 第 %d 層",
  "gui.tac_rogue.inventory.base_command": "作戦進行 // スタンバイ",
  "gui.tac_rogue.inventory.mission_start": "作戦開始",
  "gui.tac_rogue.inventory.shop": "ショップ",
  "gui.tac_rogue.inventory.buy": "購入 (%d G)",
  "gui.tac_rogue.inventory.insufficient_funds": "\u00A7c資金不足",
  "gui.tac_rogue.inventory.filter": "フィルター",

  "gui.tac_rogue.floor_clear.title": "フロアクリア",
  "gui.tac_rogue.floor_clear.secured": "エリア制圧完了",
  "gui.tac_rogue.floor_clear.select": "次の行動を選択",
  "gui.tac_rogue.floor_clear.return": "ロビーに戻る",
  "gui.tac_rogue.floor_clear.next": "次の層へ進む",

  "message.tac_rogue.clear": "\u00A7a\u00A7l[CLEAR] \u00A7fエリア制圧完了。",
  "message.tac_rogue.mission_failed": "\u00A7c\u00A7l[ROGUE] \u00A7fミッション失敗。ロビーに帰還します。",
  "message.tac_rogue.welcome": "TacZ Roguelikeへようこそ！",
  "message.tac_rogue.low_stamina": "\u00A7cスタミナ不足！",
  "message.tac_rogue.difficulty_set": "\u00A7e[DIFFICULTY] %s \u00A7fに設定しました。",
  "message.tac_rogue.perk_acquired": "\u00A7a[PERK] %s \u00A77を取得しました。",
  "message.tac_rogue.stash_upgraded": "\u00A7b[STASH \u2191] %s SLOTSに拡張しました！",
  "message.tac_rogue.stash_max": "\u00A7c[STASH] 最大拡張済みです。",
  "message.tac_rogue.inv_upgraded": "\u00A7a[SHOP] インベントリ拡張: +2 SLOTS（合計 %s）",
  "message.tac_rogue.inv_max": "\u00A7c[SHOP] インベントリ拡張は最大に達しています。",
  "message.tac_rogue.shop_purchased": "\u00A7a[SHOP] 購入完了: %s",
  "message.tac_rogue.loadout_selected": "\u00A7b[LOADOUT] 装備選択: %s",
  "message.tac_rogue.void_return": "\u00A7c[SYSTEM] 奈落落下を検知。ロビーへ帰還しました。",
  "message.tac_rogue.steak_heal": "\u00A7a+6 HP（ステーキ効果）",
  "message.tac_rogue.stamina_boost": "\u00A7a[SYSTEM] \u00A7f一時的に最大スタミナが上昇した！",
  "message.tac_rogue.extraction_arrived": "\u00A7b[SYSTEM] \u00A7fフロア制圧完了。回収要員の Lt. Hayes が到着した。準備が完了次第話しかけろ。",
  "npc.tac_rogue.extraction_officer": "\u00A7b[回収要員] \u00A7fLt. Hayes",
  "message.tac_rogue.scrap_sold": "\u00A7e[GOLD] スクラップを換金: +%s G",
  "message.tac_rogue.gold_cache": "\u00A7e[GOLD] ゴールドキャッシュ使用: +%s G",
  "message.tac_rogue.ration_heal": "\u00A7a[FIELD RATION] +6 HP / 満腹度回復",
  "message.tac_rogue.hp_full": "\u00A77体力が最大です。",
  "message.tac_rogue.medkit_heal": "\u00A7a[MEDKIT] +%s HP（最大体力の30%%）",
  "message.tac_rogue.death_penalty": "\u00A7c[DEATH] ゴールドを5%%紛失しました（-%s GOLD）",
  "message.tac_rogue.floor_enter": "\u00A7e[ROGUELIKE] FLOOR %1$s \u2014 %2$s",

  "perk.tac_rogue.cat.vitality": "最大HP +%s%% \u2014 最大体力を増加させ、深層フロアでの生存力を向上。",
  "perk.tac_rogue.cat.regeneration": "HP自動回復 +%s/秒 \u2014 体力を時間経過で回復。30%%回復上限を解除。",
  "perk.tac_rogue.cat.armor": "防御力 +%s \u2014 受けるダメージを軽減。装備の防御力と重複。",
  "perk.tac_rogue.cat.velocity": "移動速度 +%s%% \u2014 移動速度が上昇し、素早いポジショニングが可能。",
  "perk.tac_rogue.cat.stamina": "スタミナ +%s%% \u2014 スタミナ上限が増加し、ダッシュや回避が長持ち。",
  "perk.tac_rogue.cat.damage": "攻撃力 +%s%% \u2014 すべての武器ダメージを底上げ。",
  "perk.tac_rogue.cat.gun_proficiency": "銃器熟練度 +%s%% \u2014 精度・発射速度・命中力を総合的に強化し、銃器ダメージを増加。",
  "perk.tac_rogue.cat.reload_speed": "リロード速度 +%s%% \u2014 全火器のリロード時間を短縮。",
  "perk.tac_rogue.cat.ammo_efficiency": "弾薬消費 -%s%% \u2014 射撃時に弾薬を消費しない確率が発生。",
  "perk.tac_rogue.cat.scavenger": "ドロップ率 +%s%% \u2014 敵がアイテムやリソースを落としやすくなる。",
  "perk.tac_rogue.cat.gold_rush": "ゴールド報酬 +%s%% \u2014 キルやクリア報酬のゴールドが増加。",
  "perk.tac_rogue.cat.vampire": "キル時HP回復 +%s \u2014 敵を倒すたびに体力を回復。",
  "perk.tac_rogue.cat.explosive": "爆発ダメージ +%s%% \u2014 爆発のダメージと範囲を拡大。",
  "perk.tac_rogue.cat.resistance": "状態異常耐性 +%s%% \u2014 デバフの効果時間を短縮。",
  "perk.tac_rogue.cat.fortune": "クリティカル率 +%s%% \u2014 クリティカルヒットの発生率を上昇。",
  "perk.tac_rogue.cat.handling": "取り回し +%s%% \u2014 武器切り替え速度とADS安定性を向上。エイム時にダメージボーナス。",
  "perk.tac_rogue.cat.mag_size": "マガジン容量 +%s%% \u2014 全火器のマガジン容量を増加。",
  "perk.tac_rogue.cat.bloodlust": "ブラッドラスト \u2014 キル時に移動速度+%s%%、及び体力を微量回復。",
  "perk.tac_rogue.cat.medic": "コンバットメディック \u2014 回復アイテムの効果量が%s%%増加。",
  "perk.tac_rogue.cat.dodge": "回避 \u2014 %s%%の確率で被ダメージを完全に無効化。",
  "perk.tac_rogue.cat.adrenaline": "アドレナリン \u2014 スタミナ回復速度が%s%%上昇。",
  "perk.tac_rogue.cat.stealth_extend": "ステルス拡張 \u2014 敵に見つかる範囲が%s%%縮小する。",
  "perk.tac_rogue.cat.quick_fix": "クイックフィックス \u2014 リロード完了時にHPを%s回復。",
  "perk.tac_rogue.cat.titanic": "タイタニック \u2014 全ステータスが激増(%s%%)するが、ダッシュ不可になる。",
  "perk.tac_rogue.cat.sharpshooter": "シャープシューター \u2014 遠距離(10m以上)の敵へのダメージが%s%%増加。",
  "perk.tac_rogue.cat.executioner": "処刑人 \u2014 HP30%%以下の敵へのダメージが%s%%増加。",
  "perk.tac_rogue.cat.head_hunter": "ヘッドハンター \u2014 ヘッドショットダメージの倍率が%s%%増加。",

  "perk.tac_rogue.mod.radiant": "効果強化（1.2倍）\u2014 さらに永続的な暗視効果を獲得",
  "perk.tac_rogue.mod.reinforced": "\u00A7a効果強化（1.15倍）",
  "perk.tac_rogue.mod.cursed": "\u00A7cランダムなステータス -10%",
  "perk.tac_rogue.mod.volatile": "\u00A7c発動時に自傷ダメージ",
  "perk.tac_rogue.mod.blessed": "\u00A7a極大強化（1.3倍）",
  "perk.tac_rogue.mod.fractured": "\u00A7c5フロア後に効果が消滅",
  "perk.tac_rogue.mod.primal": "\u00A76HP50%以下で効果増大",
  "perk.tac_rogue.mod.overclocked": "\u00A7cスタミナ消費 +50%",
  "perk.tac_rogue.mod.corrupted": "\u00A7c射撃時たまに自傷ダメージ",

  "gui.tac_rogue.difficulty.subtitle": "\u00A77難易度を選択",
  "gui.tac_rogue.difficulty.start": "\u00A7aRoguelike 開始",
  "tooltip.tac_rogue.snowball_distract": "\u00A77投げることで敵の注意を引くことができる",
  "difficulty.tac_rogue.easy.desc": "\u00A7a敵 HP -30%, 攻撃力 -20%\nゴールド +50%, ドロップ率 +30%\n\u00A7aデスペナルティ: なし",
  "difficulty.tac_rogue.normal.desc": "\u00A7f標準バランス\n全パラメータ x1.0\n\u00A7fデスペナルティ: 所持金の5%",
  "difficulty.tac_rogue.hard.desc": "\u00A7c敵 HP +50%, 攻撃力 +30%\nゴールド -20%, ドロップ率 -20%\n\u00A7cデスペナルティ: 所持金の15% + パーク1個喪失",
  "difficulty.tac_rogue.extreme.desc": "\u00A74敵 HP x2, 攻撃力 x2\nゴールド -50%, ドロップ率 -50%\n\u00A74デスペナルティ: 所持金の30% + パーク3個喪失\n\u00A74+ 携帯アイテム全喪失 (武器・弾薬は継続)",

  "message.tac_rogue.lobby_only_exchange": "\u00A7cロビーに戻ってからゴールドに換金できます。",
  "message.tac_rogue.perk_lost": "\u00A7c[DEATH PENALTY] パークを %s 個喪失しました。",
  "message.tac_rogue.items_lost": "\u00A74[DEATH PENALTY] 携帯アイテムを全て喪失しました。",

  "message.tac_rogue.quest_complete": "\u00A7a[QUEST COMPLETE] %s \u2014 報酬: %sG",
  "message.tac_rogue.chapter_unlock": "\u00A76[CHAPTER %s] 新チャプター解放！",
  "message.tac_rogue.ng_plus": "\u00A7d[NG+ %s] 全チャプタークリア！周回モードに突入！",
  "message.tac_rogue.quest_terminal_header": "\u00A76══ クエストターミナル \u2014 Chapter %s/%s ══",
  "message.tac_rogue.intel_header": "\u00A7b[INTEL] 作戦情報ブリーフィング",
  "message.tac_rogue.medic_heal": "\u00A7d[MEDIC] HP とスタミナを全回復しました。",

  "quest.tac_rogue.type.kill": "キル",
  "quest.tac_rogue.type.kill.desc": "敵を %s 体倒す",
  "quest.tac_rogue.type.floor_clear": "フロアクリア",
  "quest.tac_rogue.type.floor_clear.desc": "フロアを %s 回クリアする",
  "quest.tac_rogue.type.headshot": "ヘッドショット",
  "quest.tac_rogue.type.headshot.desc": "ヘッドショットで %s 体倒す",
  "quest.tac_rogue.type.stealth_kill": "ステルスキル",
  "quest.tac_rogue.type.stealth_kill.desc": "見つからずに敵を %s 体倒す",
  "quest.tac_rogue.type.boss_kill": "ボス撃破",
  "quest.tac_rogue.type.boss_kill.desc": "ボスを %s 体討伐する",
  "quest.tac_rogue.type.gold_earn": "ゴールド獲得",
  "quest.tac_rogue.type.gold_earn.desc": "累計 %s ゴールド獲得する",
  "quest.tac_rogue.type.survive": "生存",
  "quest.tac_rogue.type.survive.desc": "HP50%%以上でフロアを %s 回クリアする",
  "quest.tac_rogue.type.no_damage": "ノーダメージ",
  "quest.tac_rogue.type.no_damage.desc": "ノーダメージでフロアを %s 回クリアする",
  "quest.tac_rogue.type.speedrun": "スピードラン",
  "quest.tac_rogue.type.speedrun.desc": "制限時間内（120秒＋フロアx10秒）にフロアを %s 回クリアする",
  "quest.tac_rogue.type.weapon_mastery": "武器マスタリー",
  "quest.tac_rogue.type.weapon_mastery.desc": "銃種を変えて敵を %s 体倒す",

  "chapter.tac_rogue.1.title": "\u00A76Chapter 1: 亀裂の発見",
  "chapter.tac_rogue.1.summary": "地下施設に現れた異次元の亀裂。原因不明の敵が出現し始めた。",
  "chapter.tac_rogue.2.title": "\u00A76Chapter 2: 最初の接触",
  "chapter.tac_rogue.2.summary": "亀裂から出現した敵との最初の全規模交戦。戦闘経験を積め。",
  "chapter.tac_rogue.3.title": "\u00A76Chapter 3: 精密射撃訓練",
  "chapter.tac_rogue.3.summary": "司令部の指令: ヘッドショット精度の向上が必要だ。",
  "chapter.tac_rogue.4.title": "\u00A76Chapter 4: 影の作戦",
  "chapter.tac_rogue.4.summary": "敵拠点への潜入作戦。探知されずに排除せよ。",
  "chapter.tac_rogue.5.title": "\u00A76Chapter 5: 要塞突破",
  "chapter.tac_rogue.5.summary": "亀裂深部に巨大な敵が確認された。ボスを討伐せよ。",
  "chapter.tac_rogue.6.title": "\u00A76Chapter 6: 鉄壁の盾",
  "chapter.tac_rogue.6.summary": "被弾ゼロでフロアをクリアし、防御技術を証明せよ。",
  "chapter.tac_rogue.7.title": "\u00A76Chapter 7: 軍資金確保",
  "chapter.tac_rogue.7.summary": "作戦資金が不足している。ゴールドを集めて補給路を確保せよ。",
  "chapter.tac_rogue.8.title": "\u00A76Chapter 8: 電撃作戦",
  "chapter.tac_rogue.8.summary": "敵の増援が来る前にフロアを制圧せよ。速度が命だ。",
  "chapter.tac_rogue.9.title": "\u00A76Chapter 9: 持久戦",
  "chapter.tac_rogue.9.summary": "弾薬補給なしで連続フロアを生き延びろ。",
  "chapter.tac_rogue.10.title": "\u00A7eChapter 10: 亀裂の核心",
  "chapter.tac_rogue.10.summary": "亀裂の核心部に到達。強力なボス群が待ち構えている。",
  "chapter.tac_rogue.11.title": "\u00A76Chapter 11: 武器研究",
  "chapter.tac_rogue.11.summary": "新兵器のデータ収集。様々な武器での戦闘が求められる。",
  "chapter.tac_rogue.12.title": "\u00A76Chapter 12: 狙撃手の道",
  "chapter.tac_rogue.12.summary": "長距離精密射撃の達人を目指せ。",
  "chapter.tac_rogue.13.title": "\u00A76Chapter 13: 暗殺者",
  "chapter.tac_rogue.13.summary": "高難易度ステルスミッション。音を立てるな。",
  "chapter.tac_rogue.14.title": "\u00A76Chapter 14: 殲滅戦",
  "chapter.tac_rogue.14.summary": "亀裂から大量の敵が出現。全て排除せよ。",
  "chapter.tac_rogue.15.title": "\u00A7cChapter 15: 深淵の守護者",
  "chapter.tac_rogue.15.summary": "亀裂の最深部。次々と現れるボスを打ち倒せ。",
  "chapter.tac_rogue.16.title": "\u00A76Chapter 16: 完璧な兵士",
  "chapter.tac_rogue.16.summary": "連続ノーダメージクリアで己の限界を超えろ。",
  "chapter.tac_rogue.17.title": "\u00A76Chapter 17: 大掃除",
  "chapter.tac_rogue.17.summary": "汚染された全フロアを浄化せよ。",
  "chapter.tac_rogue.18.title": "\u00A76Chapter 18: 時間との戦い",
  "chapter.tac_rogue.18.summary": "亀裂が収縮する前に全ミッションを完了せよ。",
  "chapter.tac_rogue.19.title": "\u00A7cChapter 19: 最後の進撃",
  "chapter.tac_rogue.19.summary": "亀裂の向こう側への突入作戦。全戦力を投入せよ。",
  "chapter.tac_rogue.20.title": "\u00A74Chapter 20: 終焉の裂け目",
  "chapter.tac_rogue.20.summary": "全ての亀裂を閉じ、世界を救え。最終決戦。",

  "key.categories.tac_rogue": "TacZ Roguelike",
  "key.tac_rogue.flashlight": "フラッシュライト切替",
  "key.tac_rogue.camera_toggle": "肩越しカメラ切替",
  
  "gui.tac_rogue.welcome.title": "TacZ Roguelike へようこそ",
  "gui.tac_rogue.welcome.start": "確認してゲームを開始",
  "gui.tac_rogue.welcome.press_key": "キー入力...",
  "gui.tac_rogue.welcome.key_sprint": "ダッシュ (走る):",
  "gui.tac_rogue.welcome.key_sneak": "しゃがみ (バニラ):",
  "gui.tac_rogue.welcome.key_crawl": "這いずり (TacZ):",
  "gui.tac_rogue.welcome.key_flashlight": "フラッシュライト:",
  "gui.tac_rogue.welcome.key_camera": "エイム視点トグル:",
  "gui.tac_rogue.welcome.key_perspective": "視点切替 / F5:",
  "gui.tac_rogue.welcome.key_l3p_adjust": "カメラ位置調整 (Leawind):",
  "gui.tac_rogue.welcome.key_attach": "アタッチメント:",
  "gui.tac_rogue.welcome.key_tacz_interact": "銃でインタラクト (TacZ):",
  "gui.tac_rogue.welcome.key_inspect": "銃を眺める:",
  
  "gui.tac_rogue.welcome.tut1": "[ ステルスと姿勢低下（這いずり） ]",
  "gui.tac_rogue.welcome.tut2": "しゃがむことで敵の探知範囲を狭めることができます。",
  "gui.tac_rogue.welcome.tut3": "這いずり（伏せ）状態なら少し離れるだけで完全に探知されなくなります。",
  
  "gui.tac_rogue.welcome.tut4": "[ スタミナシステム（緑のゲージ） ]",
  "gui.tac_rogue.welcome.tut5": "ダッシュやジャンプで消費します。ゼロになると一定時間走れなくなります。",
  
  "gui.tac_rogue.welcome.tut6": "[ ダイナミック ライト ]",
  "gui.tac_rogue.welcome.tut7": "階層によっては完全に真っ暗なフロアがあります。フラッシュライトで視界を確保してください！",
  "gui.tac_rogue.welcome.scroll_hint": "▼ マウスホイールで下にスクロールして操作を設定 ▼"
}

with open(r"c:\Users\user\Documents\TacZ_Roguelike_Workspace\tac_rogue_mod\src\main\resources\assets\tac_rogue\lang\ja_jp.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
