modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="enchanted_arsenal"
version="1.0.1"
displayName="Enchanted Arsenal"
displayURL="https://www.youtube.com/channel/UCIkMn8bd90FRO6dd4_kKqTw"
logoFile="logo.png"
credits="Mod by me, icon by zendy"
authors="maxinblender"
description="A mod that adds enchantments designed to work with tacz guns"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.enchanted_arsenal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



